<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Spatie\Sitemap\SitemapGenerator;

use Spatie\Sitemap\Sitemap;
use Spatie\Sitemap\Tags\Url;

use App\Models\Brand;
use App\Models\Category;
use App\Models\Shop;


class GenerateSitemap extends Command
{
    protected $signature = 'sitemap:generate';
    //protected $description = 'Generate the sitemap by crawling the site';
    protected $description = 'Generate the sitemap by specific urls';

    public function handle()
    {
	/*
        $appUrl = config('app.url'); // Get the APP_URL from the .env file
        SitemapGenerator::create($appUrl)
            ->writeToFile(base_path('sitemap.xml'));
	 */

	$sitemap = Sitemap::create();

        $brands = Brand::whereNotNull('slug')->get();
        foreach ($brands as $brand) {
            $sitemap->add(
                Url::create(route('products.brand', $brand->slug)) 
                    ->setLastModificationDate($brand->updated_at)
                    ->setChangeFrequency(Url::CHANGE_FREQUENCY_DAILY)
                    ->setPriority(0.9)
            );
        }

        $categories = Category::whereNotNull('slug')->get();
        foreach ($categories as $cat) {
            $sitemap->add(
                Url::create(route('products.category', $cat->slug)) 
                    ->setLastModificationDate($cat->updated_at)
                    ->setChangeFrequency(Url::CHANGE_FREQUENCY_DAILY)
                    ->setPriority(0.8)
            );
        }

        $eshops = Shop::whereNotNull('slug')->get();
        foreach ($eshops as $eshop) {
            $sitemap->add(
                Url::create(route('shop.visit', $eshop->slug)) 
                    ->setLastModificationDate($eshop->updated_at)
                    ->setChangeFrequency(Url::CHANGE_FREQUENCY_DAILY)
                    ->setPriority(0.7)
            );
        }

        $sitemap->writeToFile(base_path('sitemap.xml'));

        //$this->info('Sitemap generated using APP_URL and placed in the root folder!');
        $this->info('Sitemap generated by specific URLs!');
    }
}

