<?php

const APPROVED_STATUS = 1;
const UNDER_REVIEW_STATUS = 4;
const WEIGHT_ATTRIBUTE_ID = 39;
const KG_UNITY_ATTRIBUTE_ID = 14;
const WEIGHT_MARGIN = 1.03;

const ARAMEX_PRODUCT_GROUP = "DOM";
const ARAMEX_PRODUCT_TYPE = "ONP";
const ARAMEX_PAYMENT_TYPE = "P";

const LOW_STOCK_THRESHOLD = 5;

const MAWADONLINE_WAREHOUSE_ID = 24;

// in minutes
const RESERVATION_WAIT_TIME = 30;
const DELIVERY_STATUS = ['ready_for_shipment','on_the_way'];
